version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tg_bot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: linux
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moviedb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

  redis:
    image: redis:7.2-alpine
    container_name: tg_bot_redis
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    networks:
      - bot_network

  bot_app:
    build: .
    container_name: tg_cinema_bot
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - bot_network

  frontend:
    build:
      context: ../movie-linker-tma
      args:
        - VITE_API_URL=${NGROK_URL}
    container_name: tg_bot_frontend
    ports:
      - "3000:80"
    depends_on:
      - bot_app
    networks:
      - bot_network

volumes:
  pgdata:
  redisdata:

networks:
  bot_network:
    driver: bridge