services:

  postgres:
    image: postgres:16-alpine
    container_name: movie_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: linux
      POSTGRES_DB: moviedb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moviedb"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: always

    networks:
      - movie_network

  redis:
    image: redis:7-alpine
    container_name: movie_redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: always

    networks:
      - movie_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: movie_bot

    ports:
      - "9090:9090"

    env_file:
      - .env

    environment:
      FRONTEND_INTERNAL_URL: http://frontend:80

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started

      frontend:
        condition: service_started

    restart: always

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - movie_network

  frontend:
    build:
      context: ../movie-linker-tma
      dockerfile: Dockerfile

    container_name: movie_linker_tma

    ports:
      - "3000:80"

    restart: always

    networks:
      - movie_network

volumes:
  postgres_data:
  redis_data:

networks:
  movie_network:
    driver: bridge
